######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 1 11:55:30 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qt_classes
INCLUDEPATH += . qt_classes

# Input
HEADERS += qt_classes/GraphGraphicsScene.h qt_classes/MainWindow.h
SOURCES += main.cpp qt_classes/GraphGraphicsScene.cpp qt_classes/MainWindow.cpp
